version: 2

sources:
  - name: products
    project: analytics-engineers-club

    tables:
      - name: products
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: name
            tests:
              - not_null
          - name: category
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null

      - name: product_prices
        colummns:
          - name: id
            tests:
              - unique
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: price
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: ended_at
            tests:
              - not_null


